"""
backend/models/user.py

User + CreatorMemory SQLAlchemy models.

Step 11b: added `newsletter_consent` column so you can send marketing
emails later (tips, product updates, launches) to opted-in users only.
This is stored at signup and can be toggled via settings later.
"""
from __future__ import annotations

import enum
import uuid

from sqlalchemy import (
    Column, String, Integer, DateTime, ForeignKey, Enum, Float, Boolean
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from backend.core.database import Base


class Plan(str, enum.Enum):
    """User subscription plans. Values match master doc Part 9 pricing."""
    free = "free"
    starter = "starter"
    pro = "pro"
    agency = "agency"


class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String(255), unique=True, nullable=False, index=True)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String(255), nullable=True)

    plan = Column(
        Enum(Plan, name="plan_enum"),
        default=Plan.free,
        nullable=False,
    )
    credits = Column(Integer, default=3, nullable=False)  # free tier: 3 videos
    api_key = Column(String, unique=True, nullable=True, index=True)

    # Session WM: lifetime counter of clips ever generated by this user.
    # Used by watermark gating: free-tier users get the first
    # FREE_TIER_WATERMARK_THRESHOLD clips (default 1) without watermark.
    # NEVER reset — this is the anti-abuse signal. Even if user cancels and
    # re-subscribes, we don't reset (otherwise abusers cycle subscriptions).
    lifetime_clips_generated = Column(Integer, default=0, nullable=False)

    # --- NEW Step 11b: marketing consent ---
    # Tracks whether user opted into promotional emails. Stored at signup.
    # When you set up email marketing later (Step 13), query users WHERE
    # newsletter_consent=True AND email IS NOT NULL.
    newsletter_consent = Column(Boolean, default=True, nullable=False)
    newsletter_consent_at = Column(DateTime(timezone=True), nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    memory = relationship(
        "CreatorMemory",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    video_jobs = relationship(
        "VideoJob",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    clips = relationship(
        "Clip",
        back_populates="user",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<User {self.email} plan={self.plan.value}>"


class CreatorMemory(Base):
    """
    Per-user style memory — the competitive moat (master doc Part 1).
    We learn what clips perform well for each creator and weight future
    scoring toward their proven patterns.
    """
    __tablename__ = "creator_memory"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )

    preferred_length_sec = Column(Integer, default=55)
    caption_style = Column(String, default="viral")
    hook_patterns = Column(JSONB, default=list)
    pacing_score = Column(Float, default=1.0)
    successful_clips = Column(JSONB, default=list)
    total_videos = Column(Integer, default=0)

    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    user = relationship("User", back_populates="memory")

    def __repr__(self) -> str:
        return f"<CreatorMemory user_id={self.user_id} videos={self.total_videos}>"